db:
  # type: 'postgres'
  host: 'localhost'
  # port: 5432
  username: 'dev'
  password: '123'
  # database: 'dev'
  # entities: [__dirname + "/../**/*.entity.ts"],
  synchronize: true

jwt:
  secret: 'topSecret51'